### ISSUE TITLE
[Bug]: cannot import name 'opts' from partially initialized module 'modules.shared'

### ISSUE THREAD

**Issue by Convexity-ai** [lshqqytiger/stable-diffusion-webui-directml#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

SD fails to start after commit ed20ba7 with error `cannot import name 'opts' from partially initialized module 'modules.shared'` See log below for more information.

This doesn't happen on Vlad's fork after the same commit pull.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

SD starts without error.

### Version or Commit where the problem happens

ed20ba7

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--medvram --no-half --no-half-vae
```

### List of extensions

No

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Program Files\stable-diffusion-webui-directml\launch.py", line 39, in <module>
    main()
  File "C:\Program Files\stable-diffusion-webui-directml\launch.py", line 35, in main
    start()
  File "C:\Program Files\stable-diffusion-webui-directml\modules\launch_utils.py", line 443, in start
    import webui
  File "C:\Program Files\stable-diffusion-webui-directml\webui.py", line 54, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noqa: F401
  File "C:\Program Files\stable-diffusion-webui-directml\modules\call_queue.py", line 6, in <module>
    from modules import shared, progress, errors
  File "C:\Program Files\stable-diffusion-webui-directml\modules\shared.py", line 95, in <module>
    directml_do_hijack()
  File "C:\Program Files\stable-diffusion-webui-directml\modules\dml\__init__.py", line 69, in directml_do_hijack
    _set_memory_provider()
  File "C:\Program Files\stable-diffusion-webui-directml\modules\dml\__init__.py", line 14, in _set_memory_provider
    from modules.shared import opts, cmd_opts, log
ImportError: cannot import name 'opts' from partially initialized module 'modules.shared' (most likely due to a circular import) (C:\Program Files\stable-diffusion-webui-directml\modules\shared.py)
Press any key to continue . . .
```

**Comment by AvengedPotat** [comment]
Same issue with me as well

**Comment by mahendra-r-kamble** [comment]
I am facing the same issue.

**Comment by oOJonnyOo** [comment]
same here

**Comment by DokHolladae** [comment]
> Looks like an issue with the latest commit. I was able to get past this error by running `git checkout 4873e6aaba62c2fa2e4481798e85098e50e1e2c6` in a command line to revert to the prior commit.
> 
> Not sure if there's any other issues, its downloading safetensors now.

Sorry I am new to all this. How do I use this to rollback?

**Comment by lshqqytiger** [comment]
Should be fixed in 723974a8b74ffd5acc1a1fdaf36e9c2426651537
